services:
  - type: worker
    name: telegram-bot
    runtime: python
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
